"""Database package — exposes models, Base, and session utilities."""

from src.db.models import (
    Base,
    Document,
    DocumentChunk,
    Product,
    ProductSelection,
    AgentRun,
    AgentTask,
    ApprovalRequest,
    DailyReport,
    SystemConfig,
    AuditLog,
    LlmCache,
    Decision,
    Conversation,
    ChatMessage,
    KeywordLibrary,
    AdSimulation,
    AdOptimizationLog,
    KBReviewQueue,
    AuditorLog,
)
from src.db.connection import engine, SessionLocal, get_db

__all__ = [
    "Base",
    "Document",
    "DocumentChunk",
    "Product",
    "ProductSelection",
    "AgentRun",
    "AgentTask",
    "ApprovalRequest",
    "DailyReport",
    "SystemConfig",
    "AuditLog",
    "LlmCache",
    "Decision",
    "Conversation",
    "ChatMessage",
    "KeywordLibrary",
    "AdSimulation",
    "AdOptimizationLog",
    "KBReviewQueue",
    "AuditorLog",
    "engine",
    "SessionLocal",
    "get_db",
]
